### ISSUE TITLE
Sketch 46.2 Support 

### ISSUE THREAD

**Issue by AquaHacker** [mludowise/Sketch-HTML-Export#6] opened 2017-10-10 08:22 UTC
Export is blank

**Comment by w01fgang** [comment] 2017-10-18 20:14
the same in sketch 47

**Comment by marco-solare** [comment] 2017-10-26 20:52
same here - Version 47.1 - any idea about it? 
The plugin seemed to be promising - is it abandoned now?

**Comment by mludowise** [comment] 2017-10-26 21:00
This is working for me in Sketch 47.1. Note that you have to mark the layers you wish to export as slices in order for them to export to HTML. If you did that and it's still not working, it would be helpful if you could provide the exact steps you took to reproduce.

Thanks.

**Comment by mludowise** [comment] 2017-11-04 08:58
Closing this issue since I haven’t gotten any responses. Please let me know if anyone is still having problems.

**Closed as completed by mludowise** 2017-11-04 08:58 UTC
